// name + ISO 3166-1 alpha-2 code (code used to bias Google Places Autocomplete to the right country)
export const COUNTRIES = [
  { name: 'Afghanistan', code: 'af' }, { name: 'Australia', code: 'au' }, { name: 'Austria', code: 'at' },
  { name: 'Bahrain', code: 'bh' }, { name: 'Bangladesh', code: 'bd' }, { name: 'Belgium', code: 'be' },
  { name: 'Brazil', code: 'br' }, { name: 'Canada', code: 'ca' }, { name: 'China', code: 'cn' },
  { name: 'Egypt', code: 'eg' }, { name: 'France', code: 'fr' }, { name: 'Germany', code: 'de' },
  { name: 'India', code: 'in' }, { name: 'Indonesia', code: 'id' }, { name: 'Iran', code: 'ir' },
  { name: 'Iraq', code: 'iq' }, { name: 'Ireland', code: 'ie' }, { name: 'Italy', code: 'it' },
  { name: 'Japan', code: 'jp' }, { name: 'Jordan', code: 'jo' }, { name: 'Kenya', code: 'ke' },
  { name: 'Kuwait', code: 'kw' }, { name: 'Lebanon', code: 'lb' }, { name: 'Malaysia', code: 'my' },
  { name: 'Maldives', code: 'mv' }, { name: 'Mexico', code: 'mx' }, { name: 'Morocco', code: 'ma' },
  { name: 'Nepal', code: 'np' }, { name: 'Netherlands', code: 'nl' }, { name: 'New Zealand', code: 'nz' },
  { name: 'Nigeria', code: 'ng' }, { name: 'Norway', code: 'no' }, { name: 'Oman', code: 'om' },
  { name: 'Pakistan', code: 'pk' }, { name: 'Philippines', code: 'ph' }, { name: 'Poland', code: 'pl' },
  { name: 'Qatar', code: 'qa' }, { name: 'Russia', code: 'ru' }, { name: 'Saudi Arabia', code: 'sa' },
  { name: 'Singapore', code: 'sg' }, { name: 'South Africa', code: 'za' }, { name: 'South Korea', code: 'kr' },
  { name: 'Spain', code: 'es' }, { name: 'Sri Lanka', code: 'lk' }, { name: 'Sweden', code: 'se' },
  { name: 'Switzerland', code: 'ch' }, { name: 'Thailand', code: 'th' }, { name: 'Turkey', code: 'tr' },
  { name: 'Uganda', code: 'ug' }, { name: 'Ukraine', code: 'ua' }, { name: 'United Arab Emirates', code: 'ae' },
  { name: 'United Kingdom', code: 'gb' }, { name: 'United States', code: 'us' }, { name: 'Vietnam', code: 'vn' },
  { name: 'Yemen', code: 'ye' },
];
